/**
 * The bog without the cat: the verse, a step too far and back to the bank,
 * the three planks, a right answer and one asked back, a quick night — and
 * walking the new bridge yourself.
 */
export default [
  () => __h.start('Velns'),
  { wait: 2600 },
  { shot: 'daina' },
  () => __h.card('Velns'),
  { wait: 1400 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 1600 },
  { shot: 'planks' },
  // Straight to the second plank: too far, and back to the bank.
  () => __h.spot('Velns', 'plank1').activate(),
  { wait: 900 },
  { shot: 'too-far' },
  () => __h.spot('Velns', 'plank0').activate(),
  { wait: 800 },
  () => __h.spot('Velns', 'plank1').activate(),
  { wait: 800 },
  { shot: 'halfway' },
  () => __h.spot('Velns', 'plank2').activate(),
  { wait: 2600 },
  { shot: 'devil' },
  () => __h.log('greeting lines', __h.scene('Velns').narration.queue.length + 1),
  () => __h.next('Velns'),
  { wait: 600 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.log('riddle', __h.nar('Velns')),
  { shot: 'riddle' },
  () => __h.pick('Velns', 1),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.pick('Velns', 0),
  { wait: 900 },
  () => __h.type('Velns'),
  { shot: 'asked-back' },
  () => __h.log('lines to terms', __h.drain('Velns')),
  { wait: 400 },
  { shot: 'night-prompt' },
  { wait: 9000 },
  () => __h.log('planks at 9s', __h.scene('Velns').built.length),
  () => __h.spot('Velns', 'bridge').activate(),
  { wait: 600 },
  { shot: 'step-ask' },
  () => __h.pick('Velns', 0),
  { wait: 900 },
  () => __h.type('Velns'),
  { shot: 'self' },
  () => __h.drain('Velns'),
  { wait: 5600 },
  { shot: 'reckoning-self' },
  () => __h.log('state', __h.state()),
];
