/** Right answer, a riddle back, a fast night, and the cat sent over. */
export default [
  () => __h.start('Velns'),
  { wait: 1500 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 5000 },
  () => __h.spot('Velns', 'plank0').activate(),
  { wait: 2200 },
  () => __h.spot('Velns', 'plank1').activate(),
  { wait: 2600 },
  () => __h.spot('Velns', 'plank2').activate(),
  { wait: 5800 },
  () => __h.next('Velns'),
  { wait: 500 },
  () => __h.next('Velns'),
  { wait: 500 },
  () => __h.next('Velns'),
  { wait: 800 },
  () => __h.pick('Velns', 1),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.type('Velns'),
  { shot: 'ask-back' },
  () => __h.pick('Velns', 0),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.type('Velns'),
  { shot: 'stumped' },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 18000 },
  () => __h.log('planks after 18s (quick)', __h.scene('Velns').built.length),
  { shot: 'quick-night' },
  () => {
    const v = __h.scene('Velns');
    v.narration.hide();
    v.bagUi.take('cat');
  },
  { wait: 300 },
  () => __h.scene('Velns').bagUi.offer(1000, 520),
  { wait: 1600 },
  { shot: 'cat-crossing' },
  { wait: 4200 },
  () => __h.type('Velns'),
  { shot: 'devil-follows' },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 5600 },
  { shot: 'reckoning-cost' },
  () => __h.log('state', __h.state(), 'bag', localStorage.getItem('vecasvaras.bag.v1'), 'lore', localStorage.getItem('vecasvaras.lore.v1')),
];
