/** The first crumb at the stone, and the village's answers to things tried on it. */
export default [
  () => __h.start('Village'),
  { wait: 2500 },
  { shot: 'no-news' },
  () => __h.use('Village', 'bread', 'stone'),
  { wait: 900 },
  () => __h.type('Village'),
  { shot: 'crumb-give' },
  () => __h.log('crumb lines', __h.drain('Village')),
  { wait: 400 },
  { shot: 'crumb-lies' },
  () => __h.use('Village', 'bread', 'stone'),
  { wait: 300 },
  () => __h.type('Village'),
  { shot: 'crumb-already' },
  () => __h.drain('Village'),
  () => __h.use('Village', 'bread', 'anna'),
  { wait: 300 },
  () => __h.type('Village'),
  { shot: 'bread-on-anna' },
  () => __h.drain('Village'),
  () => __h.use('Village', 'sickle', 'anna'),
  { wait: 300 },
  () => __h.type('Village'),
  { shot: 'sickle-on-anna' },
  () => __h.drain('Village'),
  () => __h.use('Village', 'cat', 'stone'),
  { wait: 900 },
  () => __h.type('Village'),
  { shot: 'cat-round-stone' },
  { wait: 2200 },
  () => __h.drain('Village'),
  () => __h.use('Village', 'bread', 'granary'),
  { wait: 300 },
  () => __h.type('Village'),
  { shot: 'bread-on-granary' },
  () => __h.drain('Village'),
  () => __h.use('Village', 'sickle', 'stone'),
  { wait: 300 },
  () => __h.type('Village'),
  { shot: 'sickle-on-stone' },
  () => __h.drain('Village'),
  { wait: 300 },
  () => __h.log('state', __h.state(), 'bag', localStorage.getItem('vecasvaras.bag.v1'), 'lore', localStorage.getItem('vecasvaras.lore.v1')),
  // The page of beliefs, by keyboard.
  () => __h.key('t'),
  { wait: 700 },
  { shot: 'lore-page' },
  () => __h.press('Village', 'EN'),
  { wait: 500 },
  { shot: 'lore-page-en' },
  () => __h.key('Escape'),
  { wait: 600 },
  { shot: 'lore-closed-en' },
];
