/** Nothing given: the sky greys, the cocks crow, the unpaid planks sink. */
export default [
  () => __h.start('Velns'),
  { wait: 1500 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 2000 },
  () => __h.spot('Velns', 'plank0').activate(),
  { wait: 800 },
  () => __h.spot('Velns', 'plank1').activate(),
  { wait: 800 },
  () => __h.spot('Velns', 'plank2').activate(),
  // The devil fades in, the cat goes back into the bag, then he speaks.
  { wait: 4200 },
  { shot: 'greet' },
  // Three lines with the cat in the bag.
  () => __h.next('Velns'),
  { wait: 600 },
  () => __h.next('Velns'),
  { wait: 600 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.log('riddle', __h.nar('Velns')),
  () => __h.pick('Velns', 1),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.log('askBack', __h.nar('Velns')),
  // "The bridge." — no riddle back, so the night runs at the normal pace.
  () => __h.pick('Velns', 1),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 25000 },
  () => __h.log('night 25s', __h.nar('Velns'), 'planks', __h.scene('Velns').built.length),
  () => __h.scene('Velns').narration.hide(),
  { wait: 25000 },
  { shot: 'greying' },
  { wait: 23000 },
  () => __h.type('Velns'),
  { shot: 'cock-crows' },
  { wait: 2500 },
  { shot: 'sinking' },
  () => __h.log('dawn lines', __h.nar('Velns')),
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 5600 },
  { shot: 'reckoning-dawn' },
  () => __h.log('state', __h.state(), 'bag', localStorage.getItem('vecasvaras.bag.v1')),
];
