/** Anna's second errand, and the road it opens on the map. Home from the field: the granary arrives, a mark is cut, and Anna threshes the cart. */
export default [
  () => __h.start('Village'),
  { wait: 2300 },
  { shot: 'granary-and-carving' },
  { wait: 900 },
  { shot: 'mark-into-stone' },
  { wait: 900 },
  () => __h.type('Village'),
  { shot: 'arrival-line' },
  () => __h.next('Village'),
  { wait: 400 },
  () => __h.next('Village'),
  { wait: 800 },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 600 },
  () => __h.next('Village'),
  { wait: 1600 },
  { shot: 'cart-counted' },
  () => __h.next('Village'),
  { wait: 500 },
  () => __h.next('Village'),
  { wait: 400 },
  { shot: 'threshing' },
  { wait: 900 },
  { shot: 'threshing-2' },
  { wait: 1800 },
  () => __h.type('Village'),
  { shot: 'loaf-handed' },
  () => __h.next('Village'),
  { wait: 1200 },
  () => __h.type('Village'),
  { shot: 'bog-errand' },
  () => __h.next('Village'),
  { wait: 900 },
  () => __h.next('Village'),
  { wait: 900 },
  () => __h.log('nar', __h.nar('Village'), 'ways', __h.scene('Village').holdings.ways),
  () => __h.pick('Village', 0),
  { wait: 800 },
  { shot: 'way-opened' },
  () => __h.log('ways after', __h.scene('Village').holdings.ways),
];
