/**
 * Home from the bog with the cat still in the bag, a whole run behind you:
 * the bridge, the cat to its step, the lights; Anna, the stone, the tally,
 * and the first morning of a fresh run.
 */
export default [
  () => __h.start('Village'),
  { wait: 1000 },
  { shot: 'arriving' },
  { wait: 1500 },
  { wait: 1100 },
  () => __h.type('Village'),
  { shot: 'bridge-news' },
  () => __h.next('Village'),
  { wait: 1300 },
  { shot: 'cat-home' },
  () => __h.log('lines read', __h.drain('Village')),
  { wait: 1500 },
  () => __h.log('bag', localStorage.getItem('vecasvaras.bag.v1'), 'shown', __h.state().shown),
  { shot: 'evening' },
  () => __h.spot('Village', 'cat').activate(),
  { wait: 600 },
  () => __h.type('Village'),
  { shot: 'cat-asleep' },
  () => __h.drain('Village'),
  { wait: 400 },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 700 },
  () => __h.type('Village'),
  { shot: 'anna-bog-back' },
  () => __h.log('anna lines', __h.drain('Village')),
  { wait: 400 },
  () => __h.spot('Village', 'stone').activate(),
  { wait: 700 },
  () => __h.type('Village'),
  { shot: 'stone' },
  () => __h.log('stone lines', __h.drain('Village')),
  { wait: 2500 },
  () => __h.log('outro active', __h.scene('Outro').sys.isActive()),
  () => __h.log('outro lines', __h.drain('Outro')),
  { wait: 7000 },
  { shot: 'tally' },
  () => __h.press('Outro', 'Sākt no jauna', 'Start over'),
  { wait: 2500 },
  () => __h.log('intro active', __h.scene('Intro').sys.isActive(), 'state', __h.state()),
  () => __h.type('Intro'),
  { shot: 'intro-again' },
  () => __h.log('intro lines', __h.drain('Intro')),
  { wait: 3000 },
  () => __h.log('village again', __h.scene('Village').sys.isActive(), 'bag', localStorage.getItem('vecasvaras.bag.v1')),
  { shot: 'fresh-village' },
  () => __h.spot('Village', 'stone').activate(),
  { wait: 700 },
  () => __h.log('stone2 lines', __h.drain('Village', 3)),
  () => __h.type('Village'),
  { shot: 'stone-again' },
  () => __h.drain('Village'),
  { wait: 400 },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 700 },
  () => __h.type('Village'),
  { shot: 'greet-again' },
  () => __h.log('greet lines', __h.drain('Village')),
  { wait: 800 },
  () => __h.log('state2', __h.state()),
];
