/**
 * Home from the bog with the cat still in the bag, a whole year behind you:
 * the bridge, the carving, the cat to its step, the lights; Anna, the stone,
 * the tally, the picture of the year, and the next year's first morning.
 */
export default [
  () => __h.start('Village'),
  { wait: 1000 },
  { shot: 'arriving' },
  { wait: 1500 },
  { shot: 'carving-crossing' },
  { wait: 1100 },
  () => __h.type('Village'),
  { shot: 'bridge-news' },
  () => __h.next('Village'),
  { wait: 1300 },
  { shot: 'cat-home' },
  () => __h.log('lines read', __h.drain('Village')),
  { wait: 1500 },
  () => __h.log('bag', localStorage.getItem('vecasvaras.bag.v1'), 'shown', __h.state().shown),
  { shot: 'evening' },
  () => __h.spot('Village', 'cat').activate(),
  { wait: 600 },
  () => __h.type('Village'),
  { shot: 'cat-asleep' },
  () => __h.drain('Village'),
  { wait: 400 },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 700 },
  () => __h.type('Village'),
  { shot: 'anna-bog-back' },
  () => __h.log('anna lines', __h.drain('Village')),
  { wait: 400 },
  () => __h.spot('Village', 'stone').activate(),
  { wait: 700 },
  () => __h.type('Village'),
  { shot: 'stone' },
  () => __h.log('stone lines', __h.drain('Village')),
  { wait: 2500 },
  () => __h.log('outro active', __h.scene('Outro').sys.isActive()),
  () => __h.log('outro lines', __h.drain('Outro')),
  { wait: 7000 },
  { shot: 'tally' },
  () => __h.catchDownload(),
  () => __h.press('Outro', 'Dalīties', 'Share'),
  { grab: 'share-card' },
  { wait: 800 },
  { shot: 'tally-saved' },
  () => __h.log('ledger', localStorage.getItem('vecasvaras.ledger.v1')),
  () => __h.press('Outro', 'Nākamais gads', 'Next year'),
  { wait: 2500 },
  () => __h.log('intro active', __h.scene('Intro').sys.isActive(), 'state', __h.state()),
  () => __h.type('Intro'),
  { shot: 'intro-again' },
  () => __h.log('intro lines', __h.drain('Intro')),
  { wait: 3000 },
  () => __h.log('village again', __h.scene('Village').sys.isActive(), 'bag', localStorage.getItem('vecasvaras.bag.v1')),
  { shot: 'year-two' },
  () => __h.spot('Village', 'stone').activate(),
  { wait: 700 },
  () => __h.log('stone2 lines', __h.drain('Village', 3)),
  () => __h.type('Village'),
  { shot: 'stone-older' },
  () => __h.drain('Village'),
  { wait: 400 },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 700 },
  () => __h.type('Village'),
  { shot: 'greet-again' },
  () => __h.log('greet lines', __h.drain('Village')),
  { wait: 800 },
  () => __h.log('state2', __h.state()),
];
