/** Both riddles fumbled — and a loaf with Jumis in it wins anyway. */
export default [
  () => __h.start('Velns'),
  { wait: 1500 },
  () => __h.next('Velns'),
  { wait: 700 },
  () => __h.next('Velns'),
  { wait: 2000 },
  () => __h.spot('Velns', 'plank0').activate(),
  { wait: 800 },
  () => __h.spot('Velns', 'plank1').activate(),
  { wait: 800 },
  () => __h.spot('Velns', 'plank2').activate(),
  { wait: 2500 },
  () => __h.next('Velns'),
  { wait: 500 },
  () => __h.next('Velns'),
  { wait: 800 },
  () => __h.pick('Velns', 0),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.pick('Velns', 0),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.next('Velns'),
  { wait: 6000 },
  () => {
    const v = __h.scene('Velns');
    v.narration.hide();
    v.listBargain();
  },
  { wait: 400 },
  { shot: 'list-no-cat' },
  () => __h.pick('Velns', 0),
  { wait: 2600 },
  () => __h.next('Velns'),
  { wait: 900 },
  () => __h.type('Velns'),
  { shot: 'jumis-whisper' },
  () => __h.next('Velns'),
  { wait: 1500 },
  () => __h.type('Velns'),
  { shot: 'devil-gone' },
  () => __h.next('Velns'),
  { wait: 5600 },
  { shot: 'reckoning-gone' },
  () => __h.log('state', __h.state()),
];
