/** By keyboard, the blade on the double ear: warned once, then the whole field. */
export default [
  () => __h.start('Jumis'),
  { wait: 1500 },
  () => { for (let i = 0; i < 4; i++) { __h.key('Enter'); window.__advance(500); } },
  { wait: 600 },
  () => __h.key('b'),
  { wait: 300 },
  () => __h.key('1'),
  { wait: 300 },
  () => { for (let i = 0; i < 60 && __h.scene('Jumis').cover.cut < 0.8; i++) { __h.key('Enter'); window.__advance(120); } },
  () => __h.key('p'),
  { wait: 1400 },
  () => { for (let i = 0; i < 4; i++) { __h.key('Enter'); window.__advance(500); } },
  { wait: 600 },
  () => __h.log('phase', __h.scene('Jumis').phase, 'holding', __h.scene('Jumis').bagUi.holding),
  () => __h.key('b'),
  { wait: 300 },
  () => __h.key('1'),
  { wait: 300 },
  () => __h.key('Tab'),
  { wait: 300 },
  () => __h.key('Enter'),
  { wait: 600 },
  { shot: 'warned' },
  () => __h.log('warned', __h.scene('Jumis').titheWarned, __h.scene('Jumis').phase),
  { wait: 2600 },
  () => __h.key('Enter'),
  { wait: 1800 },
  () => __h.log('cut', __h.scene('Jumis').phase, __h.nar('Jumis')),
  { shot: 'cut' },
  () => { for (let i = 0; i < 6; i++) { __h.key('Enter'); window.__advance(600); } },
  { wait: 5000 },
  () => __h.log('state', __h.state()),
  { shot: 'reckoning' },
];
