/** The whole field without a pointer: bag, sickle, Enter to cut, P to stop, Tab to the ear. */
export default [
  () => __h.start('Jumis'),
  { wait: 1500 },
  () => { for (let i = 0; i < 4; i++) { __h.key('Enter'); window.__advance(500); } },
  { wait: 600 },
  () => __h.log('phase', __h.scene('Jumis').phase),
  () => __h.key('b'),
  { wait: 300 },
  () => __h.key('1'),
  { wait: 300 },
  () => __h.log('holding', __h.scene('Jumis').bagUi.holding),
  () => { for (let i = 0; i < 12; i++) { __h.key('Enter'); window.__advance(120); } },
  { wait: 300 },
  () => __h.log('cut after 12', __h.scene('Jumis').cover.cut),
  { shot: 'keys-cutting' },
  () => { for (let i = 0; i < 60 && __h.scene('Jumis').cover.cut < 0.8; i++) { __h.key('Enter'); window.__advance(120); } },
  { wait: 300 },
  () => __h.log('cut', __h.scene('Jumis').cover.cut, 'phase', __h.scene('Jumis').phase),
  { shot: 'keys-cut' },
  () => __h.key('p'),
  { wait: 1400 },
  () => __h.log('after p', __h.scene('Jumis').phase, __h.nar('Jumis')),
  () => { for (let i = 0; i < 4; i++) { __h.key('Enter'); window.__advance(500); } },
  { wait: 600 },
  () => __h.log('gesture?', __h.scene('Jumis').phase),
  () => __h.key('Tab'),
  { wait: 300 },
  { shot: 'keys-ear-focus' },
  () => __h.key('Enter'),
  { wait: 700 },
  () => __h.log('list', __h.nar('Jumis')),
  { shot: 'keys-list' },
  () => __h.key('1'),
  { wait: 900 },
  () => { for (let i = 0; i < 6; i++) { __h.key('Enter'); window.__advance(600); } },
  { wait: 5000 },
  { shot: 'keys-reckoning' },
  () => __h.key('Enter'),
  { wait: 800 },
  () => __h.key('Enter'),
  { wait: 2500 },
  () => __h.log('state', __h.state(), 'village', __h.scene('Village').sys.isActive()),
];
