/** The screens that are not the story: the title, the beliefs page, the log. */
export default [
  () => __h.start('Title'),
  { wait: 2400 },
  { shot: 'title' },
  () => __h.start('Velns'),
  { wait: 2600 },
  () => __h.drain('Velns'),
  { wait: 800 },
  { shot: 'bog-hud' },
  () => __h.key('k'),
  { wait: 900 },
  { shot: 'map-from-bog' },
  () => __h.key('Escape'),
  { wait: 300 },
  () => __h.key('t'),
  { wait: 700 },
  { shot: 'beliefs' },
  () => __h.key('Escape'),
  { wait: 300 },
  () => __h.key('h'),
  { wait: 700 },
  { shot: 'log' },
]
