/**
 * The whole first year from a fresh install, the way a careful player takes
 * it: the intro, Anna's errand, the sickle and the cat, the tithe, the yard,
 * the bog with the cat ahead and the good loaf thrown, the evening, the stone,
 * the tally and the first morning of the next year.
 *
 * No seed: this is a first run. Steps are serialised into the page, so each
 * looks the live scene up for itself through `__h`.
 */
export default [
  () => __h.start('Intro'),
  { wait: 2500 },
  () => __h.type('Intro'),
  { shot: 'intro' },
  () => __h.log('intro lines', __h.drain('Intro')),
  { wait: 2600 },
  { shot: 'village-first' },

  // Anna gives the errand, and it is accepted out loud.
  () => __h.spot('Village', 'anna').activate(),
  { wait: 600 },
  () => __h.log('greet lines', __h.drain('Village')),
  { wait: 400 },
  { shot: 'anna-asks' },
  () => __h.pick('Village', 0),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 600 },

  // The sickle from the lean-to — the bag arrives with it — and the cat.
  () => __h.spot('Village', 'shed').activate(),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 1400 },
  { shot: 'bag-card' },
  () => __h.key('Enter'),
  { wait: 800 },
  () => __h.spot('Village', 'cat').activate(),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 1200 },
  () => __h.log('bag', localStorage.getItem('vecasvaras.bag.v1')),
  { shot: 'sickle-and-cat' },

  // To the field.
  () => __h.spot('Village', 'pathField').activate(),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 2600 },
  { shot: 'jumis-verse' },
  () => __h.card('Jumis'),
  { wait: 1400 },
  () => __h.log('arrive lines', __h.drain('Jumis')),
  { wait: 600 },
  () => __h.scene('Jumis').bagUi.take('sickle'),
  { wait: 400 },
  () => __h.sweep('Jumis', [430, 520, 610, 700, 790, 880, 970]),
  { wait: 800 },
  () => __h.log('cut', __h.scene('Jumis').cover.cut, 'phase', __h.scene('Jumis').phase),
  { shot: 'field-down' },
  () => { const j = __h.scene('Jumis'); if (j.phase === 'cutting') j.finishCut(); },
  { wait: 1400 },
  () => __h.drain('Jumis'),
  { wait: 600 },
  { shot: 'the-ear' },
  () => {
    const j = __h.scene('Jumis');
    j.gestureFrom = { x: 1596, y: 540 };
    j.previewGesture(10, 110);
  },
  { wait: 50 },
  { shot: 'bending' },
  () => {
    const j = __h.scene('Jumis');
    j.gestureFrom = null;
    j.commitGesture(10, 160);
  },
  { wait: 1500 },
  () => __h.log('field lines', __h.drain('Jumis')),
  { wait: 5200 },
  { shot: 'field-reckoning' },
  () => __h.card('Jumis'),
  { wait: 600 },
  () => __h.card('Jumis'),
  { wait: 2400 },

  // Home: the granary, the mark, and Anna's yard.
  { wait: 1200 },
  { shot: 'granary-home' },
  () => __h.drain('Village'),
  { wait: 500 },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 600 },
  () => __h.drain('Village', 1),
  { wait: 1900 },
  () => __h.drain('Village'),
  { wait: 3600 },
  { shot: 'threshed' },
  () => __h.log('yard lines', __h.drain('Village')),
  { wait: 500 },
  () => __h.log('bog ask', __h.nar('Village')),
  () => __h.pick('Village', 0),
  { wait: 700 },
  () => __h.drain('Village'),
  () => __h.log('state after yard', __h.state(), 'bag', localStorage.getItem('vecasvaras.bag.v1')),

  // The bog.
  () => __h.spot('Village', 'pathBog').activate(),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 2600 },
  () => __h.card('Velns'),
  { wait: 1400 },
  () => __h.drain('Velns'),
  { wait: 4000 },
  () => __h.spot('Velns', 'plank0').activate(),
  { wait: 2200 },
  () => __h.spot('Velns', 'plank1').activate(),
  { wait: 2600 },
  () => __h.spot('Velns', 'plank2').activate(),
  { wait: 5800 },
  () => __h.log('greeting', __h.drain('Velns')),
  { wait: 600 },
  { shot: 'riddle' },
  () => __h.pick('Velns', 1),
  { wait: 900 },
  () => __h.drain('Velns'),
  { wait: 600 },
  () => __h.pick('Velns', 1),
  { wait: 900 },
  () => __h.drain('Velns'),
  { wait: 14000 },
  { shot: 'night' },
  () => {
    const v = __h.scene('Velns');
    v.bagUi.take('bread');
  },
  { wait: 300 },
  () => __h.scene('Velns').bagUi.offer(1000, 520),
  () => __h.log('bog outcome after', __h.waitSay('Velns')),
  () => __h.log('bog lines', __h.drain('Velns')),
  { wait: 5600 },
  { shot: 'bog-reckoning' },
  () => __h.log('state after bog', __h.state()),
  () => __h.card('Velns'),
  { wait: 600 },
  () => __h.card('Velns'),
  { wait: 2400 },

  // Evening, Anna, the stone, the tally.
  { wait: 1200 },
  () => __h.drain('Village'),
  { wait: 1500 },
  { shot: 'evening' },
  () => __h.spot('Village', 'anna').activate(),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 400 },
  () => __h.spot('Village', 'stone').activate(),
  { wait: 600 },
  () => __h.drain('Village'),
  { wait: 2600 },
  () => __h.drain('Outro'),
  { wait: 7000 },
  { shot: 'tally' },
  () => __h.log('ledger', localStorage.getItem('vecasvaras.ledger.v1'), 'lore', localStorage.getItem('vecasvaras.lore.v1')),
  () => __h.press('Outro', 'Nākamais gads', 'Next year'),
  { wait: 2600 },
  () => __h.type('Intro'),
  { shot: 'next-year' },
  () => __h.log('year two', __h.state().year, 'seen', localStorage.getItem('vecasvaras.seen.v1')),
];
