/** Stopping with a third of the field standing, and meaning it. */
export default [
  () => __h.start('Jumis'),
  { wait: 1500 },
  () => __h.next('Jumis'),
  { wait: 900 },
  () => __h.next('Jumis'),
  { wait: 1200 },
  () => __h.scene('Jumis').bagUi.take('sickle'),
  { wait: 400 },
  () => __h.sweep('Jumis', [430, 560, 700], 60, 860),
  () => __h.sweep('Jumis', [840, 960], 60, 1500),
  { wait: 1200 },
  () => __h.log('cut', __h.scene('Jumis').cover.cut, 'sheaves', __h.scene('Jumis').tally.value),
  { shot: 'part-cut' },
  () => __h.scene('Jumis').finishCut(),
  { wait: 900 },
  { shot: 'spare-ask' },
  () => __h.pick('Jumis', 1),
  { wait: 900 },
  () => __h.type('Jumis'),
  { shot: 'spare-line' },
  () => __h.next('Jumis'),
  { wait: 500 },
  () => __h.next('Jumis'),
  { wait: 500 },
  () => __h.next('Jumis'),
  { wait: 5500 },
  { shot: 'reckoning' },
  () => __h.log('state', __h.state()),
];
